num_fonts: 100 # Number of fonts randomly picked from font file
num_logos: 1 # * logs * 
num_sigs: 1  # * sigs * 
num_addressee_name: 1
num_addressee_title: 1
zoom: 1
dpi: 300
dump_path: /home/parano/docgen/test.txt
force_delete: true
warp: 
  enabled: true

