num_fonts: 100 # Number of fonts randomly picked from font file
num_logos: 1 # * logs * 
num_sigs: 1  # * sigs * 
num_addressee_name: 1
num_addressee_title: 1
zoom: 1
dpi: 300
output_folder: /home/parano/Desktop/docgen/dataset
force_delete: true
pdf2image_scale_factor: 3.131944
dump_html: false
dump_bboxes: false
dump_points: true
warp: 
  enabled: true

