name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag parano/ocrdocgen:$(date +%s) --tag parano/ocrdocgen:latest 

    - name: Images
      run: docker images
    
    - name: Exporting Docker Image
      run: | 
        docker image save -o ./ocrdocgen.tar.gz parano/ocrdocgen:latest
        
    - name: Uploading to MegaDrive
    - shell: bash
      env: 
        mega_conf: ${{ secrets.MEGA_CONF }} 
      run: | 
        sudo apt-get install rclone && echo "$mega_conf" > ~/.config/rclone/rclone.conf && rclone copy --progress ./ocrdocgen.tar.gz mega:/images/ 
