name: Docker Image CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag parano/ocrdocgen:$(date +%s) --tag parano/ocrdocgen:latest 

    - name: Images
      run: docker images
    
    - name: Exporting Docker Image
      run: | 
        docker image save -o ./ocrdocgen.tar.gz parano/ocrdocgen:latest
        
    - name: Uploading Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: docker image
        path: ./ocrdocgen.tar.gz
