name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag parano/ocrdocgen:$(date +%s) --tag parano/ocrdocgen:latest 

    - name: Images
      run: docker images
    
    - name: Exporting Docker Image
      run: | 
        docker image save -o ./ocrdocgen.tar.gz parano/ocrdocgen:latest
        
    - name: Uploading to MegaDrive
      env: 
        mega_conf: ${{ secrets.MEGA_CONF }} 
      run: sudo apt-get install -y rclone && rclone config touch && config=$(rclone config file | awk "NR>1") && printf "$mega_conf" > $config && echo "This is rclone file" && cat $config && rclone copy --progress ./ocrdocgen.tar.gz mega:/images/ 
